import moment from "moment-timezone";

// Get all available timezones from moment-timezone
export const timezones = moment.tz.names();


export const cityTimezoneMap = [
  { label: "New York, USA", value: "America/New_York" },
  { label: "London, UK", value: "Europe/London" },
  { label: "Tokyo, Japan", value: "Asia/Tokyo" },
  { label: "Sydney, Australia", value: "Australia/Sydney" },
  { label: "Los Angeles, USA", value: "America/Los_Angeles" },
  { label: "Paris, France", value: "Europe/Paris" },
  { label: "Moscow, Russia", value: "Europe/Moscow" },
  { label: "UTC", value: "UTC" },
  { label: "Berlin, Germany", value: "Europe/Berlin" },
  { label: "Beijing, China", value: "Asia/Shanghai" },
  { label: "São Paulo, Brazil", value: "America/Sao_Paulo" },
  { label: "Toronto, Canada", value: "America/Toronto" },
  { label: "Dubai, UAE", value: "Asia/Dubai" },
  { label: "Mumbai, India", value: "Asia/Kolkata" },
  { label: "Cape Town, South Africa", value: "Africa/Johannesburg" },
  { label: "Mexico City, Mexico", value: "America/Mexico_City" },
  { label: "Hong Kong, China", value: "Asia/Hong_Kong" },
  { label: "Singapore", value: "Asia/Singapore" },
  { label: "Buenos Aires, Argentina", value: "America/Argentina/Buenos_Aires" },
  { label: "Seoul, South Korea", value: "Asia/Seoul" },
  { label: "Chicago, USA", value: "America/Chicago" },
  { label: "Bangkok, Thailand", value: "Asia/Bangkok" },
  { label: "Istanbul, Turkey", value: "Europe/Istanbul" },
  { label: "Rome, Italy", value: "Europe/Rome" },
  { label: "Cairo, Egypt", value: "Africa/Cairo" },
  { label: "Johannesburg, South Africa", value: "Africa/Johannesburg" },
  { label: "Zurich, Switzerland", value: "Europe/Zurich" },
  { label: "Vienna, Austria", value: "Europe/Vienna" },
  { label: "Brussels, Belgium", value: "Europe/Brussels" },
  { label: "Stockholm, Sweden", value: "Europe/Stockholm" },
  { label: "Oslo, Norway", value: "Europe/Oslo" },
  { label: "Athens, Greece", value: "Europe/Athens" },
  { label: "Lisbon, Portugal", value: "Europe/Lisbon" },
  { label: "Helsinki, Finland", value: "Europe/Helsinki" },
  { label: "Dublin, Ireland", value: "Europe/Dublin" },
  { label: "Warsaw, Poland", value: "Europe/Warsaw" },
  { label: "Budapest, Hungary", value: "Europe/Budapest" },
  { label: "Prague, Czech Republic", value: "Europe/Prague" },
  { label: "Copenhagen, Denmark", value: "Europe/Copenhagen" },
  { label: "Madrid, Spain", value: "Europe/Madrid" },
  { label: "Amsterdam, Netherlands", value: "Europe/Amsterdam" },
  { label: "Jakarta, Indonesia", value: "Asia/Jakarta" },
  { label: "Kuala Lumpur, Malaysia", value: "Asia/Kuala_Lumpur" },
  { label: "Manila, Philippines", value: "Asia/Manila" },
  { label: "Ho Chi Minh City, Vietnam", value: "Asia/Ho_Chi_Minh" },
  { label: "Hanoi, Vietnam", value: "Asia/Ho_Chi_Minh" },
  { label: "Karachi, Pakistan", value: "Asia/Karachi" },
  { label: "Lagos, Nigeria", value: "Africa/Lagos" },
  { label: "Lima, Peru", value: "America/Lima" },
  { label: "Bogotá, Colombia", value: "America/Bogota" },
  { label: "Santiago, Chile", value: "America/Santiago" },
  { label: "Riyadh, Saudi Arabia", value: "Asia/Riyadh" },
  { label: "Baghdad, Iraq", value: "Asia/Baghdad" },
  { label: "Damascus, Syria", value: "Asia/Damascus" },
  { label: "Tehran, Iran", value: "Asia/Tehran" },
  { label: "Kuwait City, Kuwait", value: "Asia/Kuwait" },
  { label: "Doha, Qatar", value: "Asia/Qatar" },
  { label: "Tel Aviv, Israel", value: "Asia/Tel_Aviv" },
  { label: "Nairobi, Kenya", value: "Africa/Nairobi" },
  { label: "Casablanca, Morocco", value: "Africa/Casablanca" },
  { label: "Algiers, Algeria", value: "Africa/Algiers" },
  { label: "Tunis, Tunisia", value: "Africa/Tunis" },
  { label: "Accra, Ghana", value: "Africa/Accra" },
  { label: "Abidjan, Ivory Coast", value: "Africa/Abidjan" },
  { label: "Addis Ababa, Ethiopia", value: "Africa/Addis_Ababa" },
  { label: "Khartoum, Sudan", value: "Africa/Khartoum" },
  { label: "Dar es Salaam, Tanzania", value: "Africa/Dar_es_Salaam" },
  { label: "Tripoli, Libya", value: "Africa/Tripoli" },
  { label: "Maputo, Mozambique", value: "Africa/Maputo" },
  { label: "Luanda, Angola", value: "Africa/Luanda" },
  { label: "Bamako, Mali", value: "Africa/Bamako" },
  { label: "Dakar, Senegal", value: "Africa/Dakar" },
  { label: "Monrovia, Liberia", value: "Africa/Monrovia" },
  { label: "Kinshasa, DR Congo", value: "Africa/Kinshasa" },
  { label: "Brazzaville, Republic of the Congo", value: "Africa/Brazzaville" },
  { label: "Bujumbura, Burundi", value: "Africa/Bujumbura" },
  { label: "Kigali, Rwanda", value: "Africa/Kigali" },
  { label: "Yaoundé, Cameroon", value: "Africa/Douala" },
  { label: "Douala, Cameroon", value: "Africa/Douala" },
  { label: "Antananarivo, Madagascar", value: "Indian/Antananarivo" },
  { label: "Port Louis, Mauritius", value: "Indian/Mauritius" },
  { label: "Colombo, Sri Lanka", value: "Asia/Colombo" },
  { label: "Kathmandu, Nepal", value: "Asia/Kathmandu" },
  { label: "Thimphu, Bhutan", value: "Asia/Thimphu" },
  { label: "Vientiane, Laos", value: "Asia/Vientiane" },
  { label: "Yangon, Myanmar", value: "Asia/Yangon" },
  { label: "Ulaanbaatar, Mongolia", value: "Asia/Ulaanbaatar" },
  { label: "Tashkent, Uzbekistan", value: "Asia/Tashkent" },
  { label: "Ashgabat, Turkmenistan", value: "Asia/Ashgabat" },
  { label: "Baku, Azerbaijan", value: "Asia/Baku" },
  { label: "Yerevan, Armenia", value: "Asia/Yerevan" },
  { label: "Tbilisi, Georgia", value: "Asia/Tbilisi" },
  { label: "Astana, Kazakhstan", value: "Asia/Almaty" },
  { label: "Bishkek, Kyrgyzstan", value: "Asia/Bishkek" },
  { label: "Dushanbe, Tajikistan", value: "Asia/Dushanbe" },
  { label: "Kampala, Uganda", value: "Africa/Kampala" },
  { label: "Harare, Zimbabwe", value: "Africa/Harare" }
];
